-- MySQL Script generated by MySQL Workbench
-- Tue Oct 18 07:39:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAIS` (
  `ID_Pais` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Pais`),
  UNIQUE INDEX `Nombre_Pais_UNIQUE` (`Nombre_Pais` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROVINCIA` (
  `ID_Provincia` INT NOT NULL,
  `Nombre_provincia` VARCHAR(45) NOT NULL,
  `PAIS_ID_Pais` INT NOT NULL,
  PRIMARY KEY (`ID_Provincia`),
  INDEX `fk_PROVINCIA_PAIS1_idx` (`PAIS_ID_Pais` ASC) VISIBLE,
  CONSTRAINT `fk_PROVINCIA_PAIS1`
    FOREIGN KEY (`PAIS_ID_Pais`)
    REFERENCES `mydb`.`PAIS` (`ID_Pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOCALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOCALIDAD` (
  `Código_localidad` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Codigo_Postal` VARCHAR(45) NULL,
  `PROVINCIA_ID_Provincia` INT NOT NULL,
  PRIMARY KEY (`Código_localidad`),
  INDEX `fk_LOCALIDAD_PROVINCIA1_idx` (`PROVINCIA_ID_Provincia` ASC) VISIBLE,
  CONSTRAINT `fk_LOCALIDAD_PROVINCIA1`
    FOREIGN KEY (`PROVINCIA_ID_Provincia`)
    REFERENCES `mydb`.`PROVINCIA` (`ID_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `Id_Empleado` INT NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Fecha_alta` DATE NOT NULL,
  `LOCALIDAD_Código_localidad` INT NOT NULL,
  PRIMARY KEY (`Id_Empleado`),
  INDEX `fk_EMPLEADO_LOCALIDAD_idx` (`LOCALIDAD_Código_localidad` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_LOCALIDAD`
    FOREIGN KEY (`LOCALIDAD_Código_localidad`)
    REFERENCES `mydb`.`LOCALIDAD` (`Código_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coche` (
  `Matricula` INT NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Precio_hora` VARCHAR(45) NOT NULL,
  `Combustible` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservas` (
  `idReservas` INT NOT NULL,
  `Fecha_inicio` DATE NOT NULL,
  `Fecha_fin` DATE NOT NULL,
  `Precio` DECIMAL(2) NOT NULL,
  `Reservascol` VARCHAR(45) NOT NULL,
  `Coche_Matricula` INT NOT NULL,
  PRIMARY KEY (`idReservas`),
  INDEX `fk_Reservas_Coche1_idx` (`Coche_Matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Reservas_Coche1`
    FOREIGN KEY (`Coche_Matricula`)
    REFERENCES `mydb`.`Coche` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Clientecol` REAL NOT NULL,
  `Clientecol1` VARCHAR(45) NOT NULL,
  `Codigo_Cliente` VARCHAR(45) NOT NULL,
  `Reservas_idReservas` INT NOT NULL,
  `Cliente_DNI` INT NOT NULL,
  `Cliente_Codigo_Cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`, `Codigo_Cliente`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  INDEX `fk_Cliente_Reservas1_idx` (`Reservas_idReservas` ASC) VISIBLE,
  INDEX `fk_Cliente_Cliente1_idx` (`Cliente_DNI` ASC, `Cliente_Codigo_Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Reservas1`
    FOREIGN KEY (`Reservas_idReservas`)
    REFERENCES `mydb`.`Reservas` (`idReservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_DNI` , `Cliente_Codigo_Cliente`)
    REFERENCES `mydb`.`Cliente` (`DNI` , `Codigo_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
